version: 0.0
os: linux
files:
  - source: web/index.php
    destination: web/index.php
    
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:678878256416:task-definition/taskdef1:latest",
        LoadBalancerInfo: 
          ContainerName: "cont" 
          ContainerPort: 80
          

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
